# output=<not set>
font=JetBrains Mono Nerd Font:size=14
dpi-aware=no
# prompt=> 
icon-theme=hicolor
icons-enabled=yes
# fields=filename,name,generic
# password-character=*
match-mode=fuzzy
# show-actions=no
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>
; keyboard-focus=exclusive

# lines=15
width=50
horizontal-pad=10
vertical-pad=10
inner-pad=10

# image-size-ratio=0.5

# line-height=<use font metrics>
# letter-spacing=0
line-height=18

[colors]
background=100f0fff       
text=cecac3ff              
match=f2ae49ff             
selection-match=f2ae49ff   
selection=393834ff         
selection-text=e0dedbff    
border=6d6b66ff            

[border]
width=2
radius=3

[dmenu]
 mode=text  
 exit-immediately-if-empty=no
