# output=<not set>
font=JetBrains Mono Nerd Font:size=14
dpi-aware=no
# prompt=> 
icon-theme=hicolor
icons-enabled=yes
# fields=filename,name,generic
# password-character=*
match-mode=fuzzy
# show-actions=no
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>

# lines=15
width=50
horizontal-pad=10
vertical-pad=10
inner-pad=10

# image-size-ratio=0.5

# line-height=<use font metrics>
# letter-spacing=0
line-height=18

[colors]
background=161616ff
text=ffffffff
match=ee5396ff
selection-match=ee5396ff
selection=262626ff
selection-text=33b1ffff
border=525252ff

[border]
width=2
radius=5

[dmenu]
 mode=text  
 exit-immediately-if-empty=no
