# Theming
font: JetBrainsMono Nerd Font 12
background: "#010101ff"
color: "#fbf1c7"
border: "#333A3F"
separator: " ➜ "
border_width: 2
corner_r: 0
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: top-left # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 10
margin_bottom: 10
margin_left: 10
margin_top: 10

# namespace to use for the layer shell surface
# namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "e"
    desc: Launch
    submenu:
      -  key: "b"
         desc: Browser
         cmd: 'brave-browser-stable --remote-debugging-port=9222'
      -  key: "a"
         desc: Ask AI
         cmd: 'brave-browser-stable --remote-debugging-port=9222 --new-window "https://chatgpt.com/?temporary-chat=true"'
      -  key: "p"
         desc: SuperProd
         cmd: '~/scripts/launch-or-focus.sh superProductivity "flatpak run com.super_productivity.SuperProductivity"'
  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: 'swaylock --grace 0; systemctl suspend'
      - key: "o"
        desc: "power-danger-layer"
        submenu:
          - key: "r"
            desc: Reboot
            cmd: reboot
          - key: "o"
            desc: Off
            cmd: poweroff
      - key: "l"
        desc: Lock
        cmd: swaylock --grace 1
  - key: "l"
    desc: Laptop Screen
    submenu:
      - key: "s"
        desc: Scale
        submenu:
          - key: "1"
            desc: Set Scale to 1.0
            cmd: wlr-randr --output eDP-1 --scale 1
          - key: "2"
            desc: Set Scale to 1.1
            cmd: wlr-randr --output eDP-1 --scale 1.1
          - key: "3"
            desc: Set Scale to 1.2
            cmd: wlr-randr --output eDP-1 --scale 1.2
          - key: "4"
            desc: Set Scale to 1.3
            cmd: wlr-randr --output eDP-1 --scale 1.3
