set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'

unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g allow-passthrough on

set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
